//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("3d12a462-a15d-4f7f-b31c-609ed963f7b2")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Niyah.SpicetifyBridge")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+015825e0486e179bcd751d0a7b030b8caf908dd1")]
[assembly: System.Reflection.AssemblyProductAttribute("Niyah.SpicetifyBridge")]
[assembly: System.Reflection.AssemblyTitleAttribute("Niyah.SpicetifyBridge")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

